databaseChangeLog:
- changeSet:
    id: 1564424018182-1
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: app_userPK
            name: id
            type: BIGINT
        - column:
            name: user_name
            type: VARCHAR(255)
        - column:
            name: user_profile_id
            type: BIGINT
        tableName: app_user
- changeSet:
    id: 1564424018182-2
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: role_requestPK
            name: id
            type: BIGINT
        - column:
            name: created_date
            type: TIMESTAMP WITHOUT TIME ZONE
        - column:
            name: role
            type: VARCHAR(255)
        - column:
            name: user_id
            type: BIGINT
        tableName: role_request
- changeSet:
    id: 1564424018182-3
    author: albvs (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              primaryKey: true
              primaryKeyName: sourcePK
            name: id
            type: BIGINT
        - column:
            name: classification
            type: VARCHAR(255)
        - column:
            name: created_date
            type: TIMESTAMP WITHOUT TIME ZONE
        - column:
            name: description
            type: VARCHAR(255)
        - column:
            name: name
            type: VARCHAR(255)
        - column:
            name: period
            type: VARCHAR(255)
        - column:
            name: type
            type: VARCHAR(255)
        tableName: source
- changeSet:
    id: 1564424018182-4
    author: albvs (generated)
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: user_id
        baseTableName: role_request
        constraintName: FK9yofb27td15c97c9e0qjsdy3k
        deferrable: false
        initiallyDeferred: false
        referencedColumnNames: id
        referencedTableName: app_user
        validate: true

